---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/current":
    get:
      summary: Returns a fibonacci number based on position.
      produces:
        - application/json
      responses:
        '200':
          description: successful
  "/api/v1/next":
    get:
      summary: next fib_number
      responses:
        '200':
          description: successful
  "/api/v1/previous":
    get:
      summary: previous fib_number
      responses:
        '200':
          description: successful
  "/api/v1/reset":
    get:
      summary: reset fib_number
      responses:
        '200':
          description: successful
