---
openapi: 3.0.1
info:
  title: Fib App API
  version: v1
paths:
  "/api/v1/current":
    get:
      summary: get current fibonacci number based on given position
      produces:
        - application/json
      parameters:
      - name: "position"
        in: "query"
        description: "The nth position of the fibonacci number"
        schema:
          type: integer
          examples:
            position-example: 1
      responses:
        200:
          content:
            application/json:
              example:
                number: 1
        '400':
          description: invalid position given
  "/api/v1/next":
    get:
      summary: get next fibonacci number based on given position
      produces:
        - application/json
      parameters:
      - name: "position"
        in: "query"
        description: "The nth position of the fibonacci number"
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '400':
          description: invalid position given
  "/api/v1/previous":
    get:
      summary: get previous fibonacci number based on given position
      produces:
        - application/json
      parameters:
      - name: "position"
        in: "query"
        description: "The nth position of the fibonacci number"
        schema:
          type: integer
      responses:
        '200':
          description: successful
        '400':
          description: invalid position given
